image: docker:latest

services:
  - docker:dind

before_script:
  - apk add --no-cache bash
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  except:
    - master

pages:
  stage: deploy
  script:
    - REGISTRY_IMAGE="$CI_REGISTRY_IMAGE" ./docker-build.sh --extract-dist
    - mv dist public
  artifacts:
    paths:
    - public
  only:
    - master
