image: docker:latest

services:
  - docker:dind

before_script:
  - apk add --no-cache bash
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  only:
    - master

pages:
  stage: deploy
  script:
    - docker run --rm -v $(pwd)/public:/tmp "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" sh -c "cp -r /var/www/html/* /tmp && chown -R $UID:$UID /tmp"
  artifacts:
    paths:
    - public
  only:
    - master
