language: bash
sudo: required
services:
- docker
script:
- "./scripts/docker-build.sh --extract-dist 2>&1"
- "git rev-parse HEAD > dist/commit.txt"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/
  on:
    branch: master
