language: rust
sudo: false

matrix:
  include:

  # tests pass
  - rust: 1.30
    script:
    - cargo test --locked
    - rustup component add rustfmt-preview
    - cargo fmt --all -- --check
    env: RUST_BACKTRACE=1
