language: bash
sudo: required
services:
- docker
script:
- "./docker-build.sh --extract-dist"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/
  on:
    branch: master
env:
  global:
    secure: KSJnSWiQEQd6OwnJaSF4TMRjkmb90RgjAI+HHD3uHfGSHIaIKo/SQWD6blVIi47LcwHgssxZN0VHUs/pqQhymQCTMdRMnP/pWm2LWLtJjb28bOy9oHnQFbfAaG2/YuoTW6ZPMDsotsAeCnLV28X3R0k76vXmpApdDXnfenN1V4WZgFkc1Bzcw+y/p8m3PUBImEqGcJ7aGylYQ68Rf7CQ4r+YXllFftt3EEGGJ9BObgPVmhugYoj93jWvApJ/qD+nn0mHdepkz7oeQNEbzX4wEW+yWvOrQVA4Y/uq/OWonkq/l0Nmj4nkh+YV7/2JmsBcYedfbmuEOTkbC3T9/ZG+sFdn1BAeCgdQ/CoJ0LLb4RzjFtfmwwXVveyFowYvt2x6ZWRpVxpyfzqeyREf1hH4SOD/Bbal20bHiQPCcbVJwhGR8W6qBNe6b2XP4AkTNzYXMUpvHIrs6X10n6/JSwlOHXgJNUkO3wgV8Of2bdzlU70TmT+LUinY3L2x/6gXwwulfkppWVIdVynNrjFtjgGFuTvWm6+BxZuqAM+x0owV/Xpgs18zB2mG9w5OCoyz4ExRRljKiRDYdNoM0MgxNNpbRDldq24U5UJCbUQVtG2DWTm8l58zLaa7DXeT1ETMHO0wAvZ7fEWD6wjuVJEPSrMsHOd9YeNEFIojrEe6L04tl/4=
