[package]
name = "screen-sim"
version = "0.1.0"
authors = ["José manuel Barroso Galindo <theypsilon@gmail.com>"]
edition = "2018"

#[cfg(target_arch = "wasm32")]
[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[profile.release]
debug = false
lto = true

[target.wasm32-unknown-unknown.dependencies]
screen-sim-web-exports = { path = "crates/screen-sim-web-exports" }

[target.'cfg(target_arch = "x86_64")'.dependencies]
screen-sim-native-sdl2 = { path = "crates/screen-sim-native-sdl2" }

[workspace]
members = [
    "crates/screen-sim-core",
    "crates/screen-sim-web-error",
    "crates/screen-sim-web-render",
    "crates/screen-sim-webgl-stubs",
    "crates/screen-sim-webgl-to-sdl2",
    "crates/screen-sim-web-exports",
    "crates/screen-sim-benchmarks",
    "crates/screen-sim-integration-test",
    "crates/screen-sim-native-sdl2",
]