[package]
name = "crt-3d-sim"
version = "0.1.0"
authors = ["José manuel Barroso Galindo <theypsilon@gmail.com>"]
edition = "2018"
cargo-features = ["rename-dependency"]

[lib]
crate-type = ["cdylib"]

[profile.release]
debug = false
lto = true

[dependencies]
wasm-bindgen = "0.2.33"
js-sys = "0.3.10"
console_error_panic_hook = "0.1"
glm = { version = "0.1", package = "nalgebra-glm" }
paste = "0.1.4"
num-traits = "0.2"
num-derive = "0.2"
getters-by-type = "0.2"

[dependencies.web-sys]
version = "0.3.10"
features = [
  'console',
  'Performance',
  'Document',
  'Event',
  'EventTarget',
  'CustomEvent',
  'CustomEventInit',
  'KeyboardEvent',
  'MouseEvent',
  'WheelEvent',
  'Window',
  'WebGlBuffer',
  'WebGl2RenderingContext',
  'WebGlProgram',
  'WebGlShader',
  'WebGlVertexArrayObject',
  'WebGlUniformLocation',
  'WebGlTexture',
  'WebGlFramebuffer',
  'WebGlRenderbuffer',
]
