[package]
name = "crt-3d-sim"
version = "0.1.1"
authors = ["José manuel Barroso Galindo <theypsilon@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[profile.release]
debug = false
lto = true

[dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3"
console_error_panic_hook = "0.1"
nalgebra-glm = "0.1.2"

[dependencies.web-sys]
version = "0.3"
features = [
  'console',
  'Performance',
  'Document',
  'Event',
  'EventTarget',
  'CustomEvent',
  'CustomEventInit',
  'KeyboardEvent',
  'MouseEvent',
  'WheelEvent',
  'Window',
  'WebGlBuffer',
  'WebGl2RenderingContext',
  'WebGlProgram',
  'WebGlShader',
  'WebGlVertexArrayObject',
  'WebGlUniformLocation',
  'WebGlTexture',
  'WebGlFramebuffer',
]