[package]
name = "screen-sim"
version = "0.1.0"
authors = ["José manuel Barroso Galindo <theypsilon@gmail.com>"]
edition = "2018"
cargo-features = ["rename-dependency"]

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[profile.release]
debug = false
lto = true

[dependencies]
wasm-bindgen = "0.2.40"
js-sys = "0.3.17"
console_error_panic_hook = "0.1"
core = { path = "src/screen-sim-core", package = "screen-sim-core" }
render = { path = "src/screen-sim-web-render", package = "screen-sim-web-render" }
web = { path = "src/screen-sim-web-entrypoint", package = "screen-sim-web-entrypoint" }
