[package]
name = "screen-sim"
version = "0.1.0"
authors = ["José manuel Barroso Galindo <theypsilon@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[[bin]]
name = "screen-sim-native"
path = "src/main.rs"

[profile.release]
debug = false
lto = true

[target.wasm32-unknown-unknown.dependencies]
screen-sim-web-exports = { path = "crates/screen-sim-web-exports" }

[target.'cfg(target_arch = "x86_64")'.dependencies]
screen-sim-native-sdl2 = { path = "crates/screen-sim-native-sdl2" }

[workspace]
members = [
    "crates/enum-len-derive",
    "crates/enum-len-trait",
    "crates/screen-sim-core",
    "crates/screen-sim-webgl-render",
    "crates/screen-sim-web-error",
    "crates/screen-sim-web-exports",
    "crates/screen-sim-stub-render",
    "crates/screen-sim-opengl-render",
    "crates/screen-sim-native-sdl2",
    "crates/screen-sim-build-tools",
    "crates/screen-sim-testing",
]