[package]
name = "screen-sim"
version = "0.1.0"
authors = ["José manuel Barroso Galindo <theypsilon@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[profile.release]
debug = false
lto = true

[dependencies]
screen-sim-web-exports = { path = "src/screen-sim-web-exports" }

[workspace]
members = [
    "src/screen-sim-core",
    "src/screen-sim-web-exports",
    "src/screen-sim-web-error",
    "src/screen-sim-web-render",
    "src/screen-sim-web-stubs",
]