[package]
name = "glow-safe-adapter"
version = "0.1.0"
authors = ["José manuel Barroso Galindo <theypsilon@gmail.com>"]
edition = "2018"

[dependencies]
glow = { git = "https://github.com/theypsilon/glow.git", package = "glow" }